### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by abellc16** [ECU-CSCI-4230/SpiralBound#18] opened 2019-03-15 01:16 UTC
When attempting to merge FlashCards into demo, it did not work. 

I think I am going to 'merge' manually. It will be a pain and incorrect, but it will probably work just fine.

**Comment by KuraideWolfie** [comment] 2019-03-15 18:38
The `Notebook-GUI` branch, and then the `FlashCards` branch, were merged into the `master` branch. Resolution of errors caused by the merge of FlashCards was handled, and a commit atop the merge present that fixes the issues. _(Testing was also performed to ensure the GUI operates as expected after merging.)_

- [ ] `FlashCards_ImportTool` and `demo` should be deleted
- [ ] `Notebook-GUI` and `FlashCards` should be rebased on the master branch

**Comment by KuraideWolfie** [comment] 2019-03-15 18:51
`Notebook-GUI` has been rebased on the master branch.

**Comment by abellc16** [comment] 2019-03-17 17:11
I deleted both the demo branch and the importTool branch

**Comment by KuraideWolfie** [comment] 2019-03-21 06:26
Closing this issue because of the fact that both FlashCards and Notebook-GUI were updated during a meeting on Tuesday.

**Closed by KuraideWolfie** 2019-03-21 06:26 UTC
Labels: bug, help wanted
